dataset: classify/configs/datasets/modelnet40.yaml
total_epoch: 600
start_epoch: 0
version: 3
dataloader:
  train:
    batch_size: 48
    shuffle: True
    num_workers: 8
    drop_last: True
    pin_memory: True
    
  test:
    batch_size: 48
    shuffle: True
    num_workers: 8
    # drop_last: True
    pin_memory: True

model:
  type: MyModel
  checkpoints: work_dir/ModelNetDataset/MyModel/3/model_best.pth
  num_class: &num_class 40
  data_preprocessor:
    type: DataPreprocessor
    data_type: 'points'
    points_layer:
      pipelines:
        furthest_point_sample: 1024
  backbone:
    type: QueryBackbone
    input_encoder: 
      type: DGCNN
      num_sample: 32
      in_channels: 3
      out_channels: 256
      channels: [128, 256]
    middle_encoder: 
      num_layer: 1
      channels: &aligned_channels 256
    query_generator:
      init: heatmap
      channels: 128 # for heatmap
      num_queries: 128
      shape_class: 40
    query_encoder:
      num_stage: 3
      query_attention:
        type: PointLocalScaleAttention
        channels: *aligned_channels
        kv_channels: [*aligned_channels,*aligned_channels]
        num_heads: 8
        attn_drop: 0.1
        proj_drop: 0.1
      feats_attention:
        type: CrossAttention
        channels: *aligned_channels
        num_heads: 8
        attn_drop: 0.1
        proj_drop: 0.1
      feed_forward_channels: 1024
      query_position_embedding: 
        # channels: 3
      feats_position_embedding:
        # channels: 3
  loss_layer:
    type: ClsLoss

optimizer:
  type: Adam
  lr: 0.0001
  weight_decay: 0.00001

scheduler:
  # type: CosineAnnealingWarmRestarts
  # T_0: 40
  # T_mult: 1
  # eta_min: 1.e-8

  type: StepLR
  step_size: 40
  gamma: 0.70