
root: &root /home/lj/MyDisk/DATASET/Completion/Completion3D
dataset_name: &dataset_name Complete3DDataset

dataset:
  train:
    type: *dataset_name
    root: *root
    split_file: train.list
    classes_file: 'synsetoffset2category.txt'
    pipelines: 
      # 'collect': ['partial', 'gt', 'label', 'class_name']
  test:
    type: *dataset_name
    root: *root
    split_file: val.list
    classes_file: 'synsetoffset2category.txt'
    pipelines: 
      # 'collect': ['partial', 'gt', 'label', 'class_name']


dataloader:
  train:
    batch_size: 32
    shuffle: True
    num_workers: 0
    drop_last: True
    pin_memory: True
    
  test:
    batch_size: 32
    shuffle: True
    num_workers: 0
    drop_last: False
    pin_memory: True

    


